### ISSUE TITLE
add The Atlantic magazine to archiver

### ISSUE THREAD

**Issue by lolgithub** [dryack/avoision#123]
### Base URL
www.theatlantic.com

### Rationale
This once semi-respectable publication now publishes hit-pieces on people. I'll just quote the example, which should make their ethics concerns readily apparent.

> While some of his comments may seem par-for-the course for an unaware teen boy, many of his statements would be offensive regardless of his personal sexuality. When reached by phone on Thursday and **_given the opportunity to put his comments in context, Jimmy showed no regret or remorse._**

> “I’m not offensive toward anyone,” he said. “I’m not offensive in the slightest bit in anything I do. I’m just going to ignore it. I don’t think anyone cares about this stuff.” He then asked if The Atlantic could simply run a positive article about him, not including his use of slurs.

> When informed that this was not an option, he suggested that he respond to a list of questions in writing over email, saying, “Wouldn’t it be easier if I just filled out these answers instead of saying this?” Finally, he said “I’m just a dumb kid that makes YouTube videos and I don’t like doing interviews,” before cutting the call short and hanging up.

> Minutes after the call ended, Jimmy deleted all tweets using the word “fag” from his Twitter account.

and the final petty graph is really the icing on the cake... 

> In the meantime, Jimmy continues to make videos and raise money for more YouTube philanthropy. Two weeks ago, on his birthday, he tweeted, “I’m 20 years old now, one of these days I’ll stop being an idiot.”

I know I'm not supposed to give my own opinion here, but.. what sanctimonious bullies.

Edit : oh, I forgot. The "homophobic comments" in question?

> Jimmy regularly uses the notion of being gay as a punchline and treats the word like a slur, hurling it at people or things he’s attempting to diss. “Windows is gay,” he tweeted regarding his frustration using the operating system in December 2015.

### Example
https://www.theatlantic.com/technology/archive/2018/05/youtubes-biggest-philanthropist-has-a-history-of-homophobic-comments/561248/

**Comment by dryack** [comment]
*sigh* Damn shame, but I concur
