### ISSUE TITLE
spiked-online.com

### ISSUE THREAD

**Issue by lolgithub** [dryack/avoision#36]
http://www.spiked-online.com/newsite/article/the-twittermob-just-went-from-irritating-to-dangerous-kriss-myers-weinstein/

A quote will speak for itself.

> The former is apparently a Corbynista pseud who writes for Vice, the bible of Shoreditch shitheads, and the latter is reportedly political correspondent for GQ, which last published an interesting article when John, Paul, George and Ringo were still a thing.

**Comment by dryack** [comment]
Pope John Paul G. Ringo was a turd, everyone knows that.
