### ISSUE TITLE
add xojane.com to redirector

### ISSUE THREAD

**Issue by lolgithub** [dryack/avoision#48]
Example : 

https://www.xojane.com/it-happened-to-me/i-cruised-okcupid-and-craiglist-for-dates-so-i-could-eat

Note that there is a screenshot of the people who contacted her for dates, and her username is obscured and their names are not. So strike one for ethics.

> To find my victims, I would chitchat with each possible suitor and then hope they’d offer to take me out, which 9 out of 10 times they would. I would pick a restaurant I wanted to try out in the city and then it was on.

My... "victims" ... ?

> After months of talking to close to 100 men and setting up over 60 dates, I finally decided to end my dates-for-meals plan. I eventually told my friends what I had been up to and majority of my girlfriends thought it was a brilliant idea whereas my guy friends thought I was the lowest of lowest.

And then I wrote an article for XoJane gloating about it. And they published it.

**Comment by dryack** [comment]
Website is cancer.  Concur.
