### ISSUE TITLE
remove the gothamist sites from redirector (RIP)

### ISSUE THREAD

**Issue by lolgithub** [dryack/avoision#49]
https://archive.is/TOg3q

"DNAinfo and Gothamist Are Shut Down After Vote to Unionize"

Rot in peace, minimal value outragemongers.

**Comment by dryack** [comment]
and there was much rejoicing

**Comment by dryack** [comment]
sfist.com, laist.com, gothamist.com

They continue to "exist" for now, so we'll put this on hold.
