### ISSUE TITLE
eastbaytimes autoplaying video and ethics

### ISSUE THREAD

**Issue by lolgithub** [dryack/avoision#50]
Example : http://www.eastbaytimes.com/2017/11/15/ghost-ship-from-the-ashes-of-easystreet-a-posthumous-release/

Also ethics, for example..

http://www.eastbaytimes.com/2017/11/15/the-tehama-county-question-why-did-this-guy-have-guns/

> In the aftermath of America’s latest mass shooting, all sides in the country’s red-hot firearms debate will move into the next stage: name-calling, blame-gaming and staking our positions.

> And while gun enthusiasts will take cover behind the Second Amendment, arguing that the Tehama County tragedy just shows that no laws can stop a maniac, gun-control proponents will argue that the shooting shows what a lousy job we do of enforcing our existing, if fragile, gun laws.

Sure seems like editorial content in an article not described as commentary. Not news reportage.

**Comment by dryack** [comment]
I hate autoplaying videos, and it certainly is increasingly difficult to avoid them if one desires to read a website.  I'm not certain I want autoplay to be a factor in which sites are added - but it's something I'll think about.

I _do_ agree however that the example cited is unethical, so in they go!
